// Universidades argentinas reconocidas (públicas nacionales/provinciales + privadas),
// compiladas a partir del listado del CIN (cin.edu.ar/instituciones-universitarias) y
// del anexo de universidades privadas de Wikipedia. No es necesariamente exhaustivo
// (nuevas universidades se crean, y hay institutos terciarios que no entran acá) —
// por eso siempre hay que ofrecer una opción "Otro" con texto libre al lado de esta lista.
export const ARGENTINE_UNIVERSITIES: string[] = [
  "Instituto Tecnológico de Buenos Aires",
  "Instituto Universitario de la Gendarmería Nacional Argentina",
  "Instituto Universitario de la Policía Federal Argentina",
  "Instituto Universitario de Seguridad de la Ciudad",
  "Instituto Universitario de Seguridad Marítima",
  "Instituto Universitario Patagónico de las Artes",
  "Instituto Universitario Policial Provincial Juan Vucetich",
  "Instituto Universitario Provincial de Seguridad",
  "Pontificia Universidad Católica Argentina",
  "Universidad Abierta Interamericana",
  "Universidad Adventista del Plata",
  "Universidad Argentina de la Empresa",
  "Universidad Argentina John F. Kennedy",
  "Universidad Atlántida Argentina",
  "Universidad Austral",
  "Universidad Autónoma de Entre Ríos",
  "Universidad Blas Pascal",
  "Universidad CAECE",
  "Universidad Católica de Córdoba",
  "Universidad Católica de Cuyo",
  "Universidad Católica de La Plata",
  "Universidad Católica de las Misiones",
  "Universidad Católica de Salta",
  "Universidad Católica de Santa Fe",
  "Universidad Católica de Santiago del Estero",
  "Universidad Champagnat",
  "Universidad de Belgrano",
  "Universidad de Buenos Aires",
  "Universidad de Ciencias Empresariales y Sociales",
  "Universidad de Concepción del Uruguay",
  "Universidad de Congreso",
  "Universidad de Flores",
  "Universidad de la Ciudad de Buenos Aires",
  "Universidad de la Cuenca del Plata",
  "Universidad de la Defensa Nacional",
  "Universidad de la Integración Sudamericana",
  "Universidad de la Marina Mercante",
  "Universidad de Mendoza",
  "Universidad de Morón",
  "Universidad de Palermo",
  "Universidad de San Andrés",
  "Universidad de San Isidro",
  "Universidad del Aconcagua",
  "Universidad del CEMA",
  "Universidad del Centro Educativo Latinoamericano",
  "Universidad del Chubut",
  "Universidad del Cine",
  "Universidad del Este",
  "Universidad del Gran Rosario",
  "Universidad del Museo Social Argentino",
  "Universidad del Norte Santo Tomás de Aquino",
  "Universidad del Salvador",
  "Universidad Empresarial Siglo 21",
  "Universidad FASTA",
  "Universidad Favaloro",
  "Universidad Gastón Dachary",
  "Universidad ISALUD",
  "Universidad Juan Agustín Maza",
  "Universidad Maimónides",
  "Universidad Metropolitana para la Educación y el Trabajo",
  "Universidad Nacional Arturo Jauretche",
  "Universidad Nacional de Avellaneda",
  "Universidad Nacional de Catamarca",
  "Universidad Nacional de Chilecito",
  "Universidad Nacional de Cuyo",
  "Universidad Nacional de Entre Ríos",
  "Universidad Nacional de Formosa",
  "Universidad Nacional de General Sarmiento",
  "Universidad Nacional de Hurlingham",
  "Universidad Nacional de José C. Paz",
  "Universidad Nacional de Jujuy",
  "Universidad Nacional de La Matanza",
  "Universidad Nacional de La Pampa",
  "Universidad Nacional de La Plata",
  "Universidad Nacional de La Rioja",
  "Universidad Nacional de Lanús",
  "Universidad Nacional de Lomas de Zamora",
  "Universidad Nacional de Luján",
  "Universidad Nacional de Mar del Plata",
  "Universidad Nacional de Misiones",
  "Universidad Nacional de Moreno",
  "Universidad Nacional de Pilar",
  "Universidad Nacional de Quilmes",
  "Universidad Nacional de Rafaela",
  "Universidad Nacional de Río Cuarto",
  "Universidad Nacional de Río Negro",
  "Universidad Nacional de Río Tercero",
  "Universidad Nacional de Rosario",
  "Universidad Nacional de Salta",
  "Universidad Nacional de San Antonio de Areco",
  "Universidad Nacional de San Juan",
  "Universidad Nacional de San Luis",
  "Universidad Nacional de San Martín",
  "Universidad Nacional de Santiago del Estero",
  "Universidad Nacional de Tierra del Fuego",
  "Universidad Nacional de Tres de Febrero",
  "Universidad Nacional de Tucumán",
  "Universidad Nacional de Villa María",
  "Universidad Nacional de Villa Mercedes",
  "Universidad Nacional del Alto Uruguay",
  "Universidad Nacional del Centro de la Provincia de Buenos Aires",
  "Universidad Nacional del Chaco Austral",
  "Universidad Nacional del Comahue",
  "Universidad Nacional de los Comechingones",
  "Universidad Nacional de Córdoba",
  "Universidad Nacional del Delta",
  "Universidad Nacional del Litoral",
  "Universidad Nacional Madres de Plaza de Mayo",
  "Universidad Nacional del Nordeste",
  "Universidad Nacional del Noroeste de la Provincia de Buenos Aires",
  "Universidad Nacional del Oeste",
  "Universidad Nacional de la Patagonia Austral",
  "Universidad Nacional de la Patagonia San Juan Bosco",
  "Universidad Nacional Raúl Scalabrini Ortiz",
  "Universidad Nacional del Sur",
  "Universidad Nacional de las Artes",
  "Universidad Nacional Guillermo Brown",
  "Universidad Notarial Argentina",
  "Universidad Pedagógica Nacional",
  "Universidad Provincial de Córdoba",
  "Universidad Provincial de Ezeiza",
  "Universidad Provincial de Laguna Blanca",
  "Universidad Provincial del Sudoeste",
  "Universidad Salesiana",
  "Universidad San Pablo-T",
  "Universidad Tecnológica Nacional",
  "Universidad Torcuato Di Tella",
];
