name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Cambia esto si deseas desplegar desde otra rama

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get install lftp

      - name: FTP Deploy
        env:
          FTP_SERVER: ftpupload.net  # Cambia esto al servidor FTP de InfinityFree
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror -R ./ /htdocs/"