name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3  # Actualizado a v3

    - name: Install FTP client
      run: sudo apt-get install -y ftp

    - name: Upload files via FTP
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        ftp -inv $FTP_HOST <<EOF
        user $FTP_USERNAME $FTP_PASSWORD
        binary
        cd htdocs
        mput *    # Sube todos los archivos
        bye
        EOF
